[project]
name = "hands-on-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.7",
    "numpy>=2.2.6",
    "scikit-image>=0.25.2",
    "scikit-learn>=1.7.2",
]
